version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: ultra_secure_password
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile.ultra
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://chatbot_user:ultra_secure_password@postgresql:5432/chatbot_db
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WORKERS=4
    depends_on:
      - redis
      - postgresql
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./faiss_index.pkl:/app/faiss_index.pkl
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

volumes:
  redis_data:
  postgres_data: